# Generated by Django 4.0 on 2023-05-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0001_initial'),
        ('core_user', '0003_user_posts_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments_liked',
            field=models.ManyToManyField(related_name='liked_by', to='core_comment.Comment'),
        ),
    ]
